<a href="https://colab.research.google.com/github/ria3999/Machine_Learning-Portfolio/blob/master/JantahackIndependenceDay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder

In [ ]:
train=pd.read_csv('/content/train.csv')
test=pd.read_csv('/content/test.csv')

In [ ]:
train.head()

ID  ... Quantitative Finance
0   1  ...                    0
1   2  ...                    0
2   3  ...                    0
3   4  ...                    0
4   5  ...                    0

[5 rows x 9 columns]

In [ ]:
test.head()

ID  ...                                           ABSTRACT
0  20973  ...    We present novel understandings of the Gamma...
1  20974  ...    Meteorites contain minerals from Solar Syste...
2  20975  ...    Frame aggregation is a mechanism by which mu...
3  20976  ...    Milky Way open clusters are very diverse in ...
4  20977  ...    Proving that a cryptographic protocol is cor...

[5 rows x 3 columns]

In [ ]:
print('Train shape:',train.shape)
print('Test shape:',test.shape)

Train shape: (20972, 9)
Test shape: (8989, 3)


In [ ]:
train.isnull().sum()

ID                      0
TITLE                   0
ABSTRACT                0
Computer Science        0
Physics                 0
Mathematics             0
Statistics              0
Quantitative Biology    0
Quantitative Finance    0
dtype: int64

In [ ]:
test.isnull().sum()

ID          0
TITLE       0
ABSTRACT    0
dtype: int64

In [ ]:
l = ['Computer Science', 'Physics', 'Mathematics', 'Statistics', 'Quantitative Biology', 'Quantitative Finance']

for col in l:
  print(col,':\n',train[col].value_counts())

Computer Science :
 0    12378
1     8594
Name: Computer Science, dtype: int64
Physics :
 0    14959
1     6013
Name: Physics, dtype: int64
Mathematics :
 0    15354
1     5618
Name: Mathematics, dtype: int64
Statistics :
 0    15766
1     5206
Name: Statistics, dtype: int64
Quantitative Biology :
 0    20385
1      587
Name: Quantitative Biology, dtype: int64
Quantitative Finance :
 0    20723
1      249
Name: Quantitative Finance, dtype: int64


In [ ]:
train['combined'] = train['TITLE']+' '+train['ABSTRACT']
test['combined'] = test['TITLE']+' '+test['ABSTRACT']

In [ ]:
X = train.loc[:,['combined']]
y = train.loc[:,l]

In [ ]:
X

combined
0      Reconstructing Subject-Specific Effect Maps   ...
1      Rotation Invariance Neural Network   Rotation ...
2      Spherical polyharmonics and Poisson kernels fo...
3      A finite element approximation for the stochas...
4      Comparative study of Discrete Wavelet Transfor...
...                                                  ...
20967  Contemporary machine learning: a guide for pra...
20968  Uniform diamond coatings on WC-Co hard alloy c...
20969  Analysing Soccer Games with Clustering and Con...
20970  On the Efficient Simulation of the Left-Tail o...
20971  Why optional stopping is a problem for Bayesia...

[20972 rows x 1 columns]

In [ ]:
y

Computer Science  Physics  ...  Quantitative Biology  Quantitative Finance
0                     1        0  ...                     0                     0
1                     1        0  ...                     0                     0
2                     0        0  ...                     0                     0
3                     0        0  ...                     0                     0
4                     1        0  ...                     0                     0
...                 ...      ...  ...                   ...                   ...
20967                 1        1  ...                     0                     0
20968                 0        1  ...                     0                     0
20969                 1        0  ...                     0                     0
20970                 0        0  ...                     0                     0
20971                 0        0  ...                     0                     0

[20972 rows x 6 columns]

In [ ]:
train.columns

Index(['ID', 'TITLE', 'ABSTRACT', 'Computer Science', 'Physics', 'Mathematics',
       'Statistics', 'Quantitative Biology', 'Quantitative Finance',
       'combined'],
      dtype='object')

In [ ]:
test.columns

Index(['ID', 'TITLE', 'ABSTRACT', 'combined'], dtype='object')

In [ ]:
X.columns

Index(['combined'], dtype='object')

In [ ]:

y.columns

Index(['Computer Science', 'Physics', 'Mathematics', 'Statistics',
       'Quantitative Biology', 'Quantitative Finance'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=555, shuffle=True)

In [ ]:
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(18874, 1) (2098, 1)
(18874, 6) (2098, 6)


In [ ]:
y_test.reset_index(drop=True,inplace=True)
X_test.reset_index(drop=True,inplace=True)

In [ ]:
y1 = np.array(y_train)
y2 = np.array(y_test)

In [ ]:
X_train.replace('[^a-zA-Z]',' ', regex=True, inplace=True)
X_test.replace('[^a-zA-Z]',' ', regex=True, inplace=True)
test.replace('[^a-zA-Z]',' ', regex=True, inplace=True)

In [ ]:
for index in X_train.columns:
  X_train[index] = X_train[index].str.lower()
for index in X_test.columns:
  X_test[index] = X_test[index].str.lower()

for index in test.columns:
  test[index] = test[index].astype(str).str.lower()

In [ ]:
test.columns

Index(['ID', 'TITLE', 'ABSTRACT', 'combined'], dtype='object')

In [ ]:
#test.drop(['ID', 'TITLE', 'ABSTRACT'],axis=1,inplace=True)

In [ ]:
test.columns

Index(['ID', 'TITLE', 'ABSTRACT', 'combined'], dtype='object')

In [ ]:
X_train['combined'] = X_train['combined'].str.replace(r'\b\w\b', '').str.replace(r'\s+', ' ')
X_test['combined'] = X_test['combined'].str.replace(r'\b\w\b', '').str.replace(r'\s+', ' ')
test['combined']=test['combined'].str.replace(r'\b\w\b', '').str.replace(r'\s+', ' ')

In [ ]:
X_train = X_train.replace('\s+', ' ', regex=True)
X_test = X_test.replace('\s+', ' ', regex=True)
test = test.replace('\s+', ' ', regex=True)


In [ ]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
from nltk import sent_tokenize, word_tokenize
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [ ]:
stop_words = set(stopwords.words('english')) 
len(stop_words)
X_train['combined'] = X_train['combined'].apply(lambda x: ' '.join(term for term in x.split() if term not in stop_words))
X_test['combined'] = X_test['combined'].apply(lambda x: ' '.join(term for term in x.split() if term not in stop_words))

In [ ]:
test['combined'] = test['combined'].apply(lambda x: ' '.join(term for term in x.split() if term not in stop_words))

In [ ]:
train_lines = []
for row in range(0,X_train.shape[0]):
  train_lines.append(' '.join(str(x) for x in X_train.iloc[row,:]))

test_lines = []
for row in range(0,X_test.shape[0]):
  test_lines.append(' '.join(str(x) for x in X_test.iloc[row,:]))

In [ ]:
test_Set=[]
for row in range(0,test.shape[0]):
  test_Set.append(' '.join(str(x) for x in test.iloc[row,:]))

In [ ]:
X.replace('[^a-zA-Z]',' ', regex=True, inplace=True)

for index in X.columns:
  X[index] = X[index].str.lower()

X['combined'] = X['combined'].str.replace(r'\b\w\b', '').str.replace(r'\s+', ' ')

#X['combined'] = X['combined'].apply(lambda x: decontracted(x))

X = X.replace('\s+', ' ', regex=True)

X['combined'] = X['combined'].apply(lambda x: ' '.join(term for term in x.split() if term not in stop_words))

#X['combined'] = X['combined'].apply(get_adjectives)

X_lines = []
for row in range(0,X.shape[0]):
  X_lines.append(' '.join(str(x) for x in X.iloc[row,:]))

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

countvector = CountVectorizer(ngram_range=(1,2))
X_train_cv = countvector.fit_transform(train_lines)
X_test_cv = countvector.transform(test_lines)
test_cv=countvector.transform(test_Set)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, TfidfTransformer

tfidfvector = TfidfTransformer()
X_train_tf = tfidfvector.fit_transform(X_train_cv)
X_test_tf = tfidfvector.fit_transform(X_test_cv)
test_tf=tfidfvector.fit_transform(test_cv)

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.multioutput import MultiOutputClassifier

model = LinearSVC(class_weight='balanced',C=0.5)
models = MultiOutputClassifier(model)

In [ ]:
X_cv = countvector.transform(X_lines)

X_tf = tfidfvector.fit_transform(X_cv)

In [ ]:
X_cv1=countvector.transform(test_Set)
X_tf1=tfidfvector.fit_transform(X_cv1)

In [ ]:
models.fit(X_tf, y)

MultiOutputClassifier(estimator=LinearSVC(C=0.5, class_weight='balanced',
                                          dual=True, fit_intercept=True,
                                          intercept_scaling=1,
                                          loss='squared_hinge', max_iter=1000,
                                          multi_class='ovr', penalty='l2',
                                          random_state=None, tol=0.0001,
                                          verbose=0),
                      n_jobs=None)

In [ ]:
preds = models.predict(X_tf1)
preds

array([[0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0]])

In [ ]:

preds1 = models.predict(X_test_tf)
preds1


array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       ...,
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 0]])

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#print(confusion_matrix(y2,preds))
print(classification_report(y2,preds1))
print(accuracy_score(y2,preds1))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96       833
           1       0.97      1.00      0.98       623
           2       0.95      0.99      0.97       573
           3       0.86      1.00      0.92       525
           4       0.78      1.00      0.88        51
           5       0.92      1.00      0.96        23

   micro avg       0.92      1.00      0.96      2628
   macro avg       0.90      1.00      0.95      2628
weighted avg       0.92      1.00      0.96      2628
 samples avg       0.95      1.00      0.97      2628

0.8913250714966635


In [ ]:
preds

array([[0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0]])

In [ ]:
test.columns

Index(['ID', 'TITLE', 'ABSTRACT', 'combined'], dtype='object')

In [ ]:
submit = pd.DataFrame({'ID': test.ID, 'Computer Science': preds[:,0],'Physics':preds[:,1],'Mathematics':preds[:,2],'Statistics':preds[:,3],'Quantitative Biology':preds[:,4],'Quantitative Finance':preds[:,5]})

In [ ]:
submit.head()

ID  Computer Science  ...  Quantitative Biology  Quantitative Finance
0  20973                 0  ...                     0                     0
1  20974                 0  ...                     0                     0
2  20975                 1  ...                     0                     0
3  20976                 0  ...                     0                     0
4  20977                 1  ...                     0                     0

[5 rows x 7 columns]

In [ ]:
submit.to_csv('submission_janta.csv', index=False)