<a href="https://colab.research.google.com/github/ria3999/mahine_learning-codes/blob/master/Recommendation_system_using_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
movies_df = pd.read_csv('movies.csv',usecols=['movieId','title'],dtype={'movieId': 'int32', 'title': 'str'})
rating_df=pd.read_csv('ratings.csv',usecols=['userId', 'movieId', 'rating'],
    dtype={'userId': 'int32', 'movieId': 'int32', 'rating': 'float32'})

In [3]:
movies_df.head()

movieId                               title
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

In [4]:
rating_df.head()

userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [5]:
df = pd.merge(rating_df,movies_df,on='movieId')
df.head()

userId  movieId  rating             title
0       1        1     4.0  Toy Story (1995)
1       5        1     4.0  Toy Story (1995)
2       7        1     4.5  Toy Story (1995)
3      15        1     2.5  Toy Story (1995)
4      17        1     4.5  Toy Story (1995)

In [6]:
combine_movie_rating = df.dropna(axis = 0, subset = ['title'])

In [7]:
combine_movie_rating

userId  movieId  rating                             title
0            1        1     4.0                  Toy Story (1995)
1            5        1     4.0                  Toy Story (1995)
2            7        1     4.5                  Toy Story (1995)
3           15        1     2.5                  Toy Story (1995)
4           17        1     4.5                  Toy Story (1995)
...        ...      ...     ...                               ...
100831     610   160341     2.5                  Bloodmoon (1997)
100832     610   160527     4.5  Sympathy for the Underdog (1971)
100833     610   160836     3.0                     Hazard (2005)
100834     610   163937     3.5                Blair Witch (2016)
100835     610   163981     3.5                         31 (2016)

[100836 rows x 4 columns]

In [8]:
movie_ratingCount = (combine_movie_rating.
     groupby(by = ['title'])['rating'].
     count().
     reset_index().
     rename(columns = {'rating': 'totalRatingCount'})
     [['title', 'totalRatingCount']]
    )

In [9]:
movie_ratingCount.tail()

title  totalRatingCount
9714                            eXistenZ (1999)                22
9715                                 xXx (2002)                24
9716             xXx: State of the Union (2005)                 5
9717                      ¡Three Amigos! (1986)                26
9718  À nous la liberté (Freedom for Us) (1931)                 1

In [10]:
rating_with_totalRatingCount = combine_movie_rating.merge(movie_ratingCount, left_on = 'title', right_on = 'title', how = 'left')
rating_with_totalRatingCount.head()

userId  movieId  rating             title  totalRatingCount
0       1        1     4.0  Toy Story (1995)               215
1       5        1     4.0  Toy Story (1995)               215
2       7        1     4.5  Toy Story (1995)               215
3      15        1     2.5  Toy Story (1995)               215
4      17        1     4.5  Toy Story (1995)               215

In [11]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)
print(movie_ratingCount['totalRatingCount'].describe())

count   9719.000
mean      10.375
std       22.406
min        1.000
25%        1.000
50%        3.000
75%        9.000
max      329.000
Name: totalRatingCount, dtype: float64


In [12]:
popularity_threshold = 50
rating_popular_movie= rating_with_totalRatingCount.query('totalRatingCount >= @popularity_threshold')
rating_popular_movie.head()

userId  movieId  rating             title  totalRatingCount
0       1        1   4.000  Toy Story (1995)               215
1       5        1   4.000  Toy Story (1995)               215
2       7        1   4.500  Toy Story (1995)               215
3      15        1   2.500  Toy Story (1995)               215
4      17        1   4.500  Toy Story (1995)               215

In [13]:
rating_popular_movie.shape

(41362, 5)

In [14]:
movie_features_df=rating_popular_movie.pivot_table(index='title',columns='userId',values='rating').fillna(0)
movie_features_df.head()

userId                              1     2     3    ...   608   609   610
title                                                ...                  
10 Things I Hate About You (1999) 0.000 0.000 0.000  ... 0.000 0.000 0.000
12 Angry Men (1957)               0.000 0.000 0.000  ... 0.000 0.000 0.000
2001: A Space Odyssey (1968)      0.000 0.000 0.000  ... 3.000 0.000 4.500
28 Days Later (2002)              0.000 0.000 0.000  ... 3.500 0.000 5.000
300 (2007)                        0.000 0.000 0.000  ... 5.000 0.000 4.000

[5 rows x 606 columns]

In [15]:
movie_features_df.values


array([[0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 3. , 0. , 4.5],
       ...,
       [5. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 3. , 0. , ..., 0. , 0. , 3.5],
       [0. , 0. , 0. , ..., 3. , 0. , 4. ]], dtype=float32)

In [16]:

from scipy.sparse import csr_matrix

movie_features_df_matrix = csr_matrix(movie_features_df.values)

from sklearn.neighbors import NearestNeighbors

In [17]:
movie_features_df_matrix

<450x606 sparse matrix of type '<class 'numpy.float32'>'
	with 41360 stored elements in Compressed Sparse Row format>

In [18]:

model_knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
model_knn.fit(movie_features_df_matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [19]:

movie_features_df.shape

(450, 606)

In [20]:
import numpy as np

In [21]:
movie_features_df.head()

userId                              1     2     3    ...   608   609   610
title                                                ...                  
10 Things I Hate About You (1999) 0.000 0.000 0.000  ... 0.000 0.000 0.000
12 Angry Men (1957)               0.000 0.000 0.000  ... 0.000 0.000 0.000
2001: A Space Odyssey (1968)      0.000 0.000 0.000  ... 3.000 0.000 4.500
28 Days Later (2002)              0.000 0.000 0.000  ... 3.500 0.000 5.000
300 (2007)                        0.000 0.000 0.000  ... 5.000 0.000 4.000

[5 rows x 606 columns]

In [22]:
query_index = np.random.choice(movie_features_df.shape[0])

In [23]:
print(query_index)


279


In [24]:
movie_features_df.iloc[query_index,:].values.reshape(1,-1)

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 3. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 4. , 0. , 0. , 3.5, 0. , 0. ,
        0. , 2. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 5. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 3.5, 0. , 0. , 0. , 0. ,
        0. , 2.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 5. , 0. , 0. , 2.5, 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 3.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 4. , 0. , 0. , 0. , 0. , 0. , 0. , 5. , 0. , 0. ,
        2.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 3. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 3. , 0. , 0. , 0. 

In [25]:
distances, indices = model_knn.kneighbors(movie_features_df.iloc[query_index,:].values.reshape(1, -1), n_neighbors = 6)

In [26]:
movie_features_df.head()


userId                              1     2     3    ...   608   609   610
title                                                ...                  
10 Things I Hate About You (1999) 0.000 0.000 0.000  ... 0.000 0.000 0.000
12 Angry Men (1957)               0.000 0.000 0.000  ... 0.000 0.000 0.000
2001: A Space Odyssey (1968)      0.000 0.000 0.000  ... 3.000 0.000 4.500
28 Days Later (2002)              0.000 0.000 0.000  ... 3.500 0.000 5.000
300 (2007)                        0.000 0.000 0.000  ... 5.000 0.000 4.000

[5 rows x 606 columns]

In [27]:
distances

array([[1.7881393e-07, 4.5355701e-01, 4.9264324e-01, 4.9928081e-01,
        5.0101960e-01, 5.0454801e-01]], dtype=float32)

In [28]:
for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(movie_features_df.index[query_index]))
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, movie_features_df.index[indices.flatten()[i]], distances.flatten()[i]))

Recommendations for Mr. & Mrs. Smith (2005):

1: Ocean's Eleven (2001), with distance of 0.45355701446533203:
2: I, Robot (2004), with distance of 0.49264323711395264:
3: Wedding Crashers (2005), with distance of 0.49928081035614014:
4: Matrix Revolutions, The (2003), with distance of 0.5010195970535278:
5: Pirates of the Caribbean: Dead Man's Chest (2006), with distance of 0.5045480132102966:
